// <auto-generated />
using System;
using DesafioCast.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DesafioCast.Migrations
{
    [DbContext(typeof(BibliotecaContexto))]
    [Migration("20180909202132_biblioteca")]
    partial class biblioteca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DesafioCast.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_cliente");

                    b.Property<string>("Cpf")
                        .HasColumnName("cpf_cliente");

                    b.Property<string>("Nome")
                        .HasColumnName("nm_cliente");

                    b.HasKey("Id");

                    b.ToTable("cliente","dbo");
                });

            modelBuilder.Entity("DesafioCast.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_emprestimo");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnName("dt_devolucao");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnName("dt_emprestimo");

                    b.Property<int>("IdCliente")
                        .HasColumnName("cd_cliente");

                    b.Property<int>("IdLivro")
                        .HasColumnName("cd_livro");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdLivro");

                    b.ToTable("emprestimo","dbo");
                });

            modelBuilder.Entity("DesafioCast.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cd_livro");

                    b.Property<DateTime>("Ano")
                        .HasColumnName("an_livro");

                    b.Property<int>("Status")
                        .HasColumnName("st_livro");

                    b.Property<string>("Titulo")
                        .HasColumnName("tt_livro");

                    b.HasKey("Id");

                    b.ToTable("livro","dbo");
                });

            modelBuilder.Entity("DesafioCast.Models.Emprestimo", b =>
                {
                    b.HasOne("DesafioCast.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DesafioCast.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
